language: python
sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true

install:
  - python setup.py develop
  - pip install flake8 docutils pygments

script:
  - python setup.py check -rs
  - flake8
